# Generated by Django 3.0 on 2019-12-08 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('title', models.CharField(default='', help_text='Enter the location name', max_length=75, unique='True')),
                ('src_link', models.URLField(blank=True, help_text='Enter a url for an image')),
                ('src_file', models.ImageField(blank=True, upload_to=None)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('lat', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Nonprofit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('title', models.CharField(help_text='Enter the location name', max_length=75)),
                ('src_link', models.URLField(help_text='Enter a url for an image')),
                ('src_file', models.ImageField(upload_to=None)),
                ('website', models.URLField(help_text='Enter the nonprofit website url, if applicable', null=True)),
                ('phone', models.CharField(help_text='Enter a phone number in the format 111-111-1111', max_length=12, null=True)),
                ('address', models.CharField(help_text='Enter the nonprofit address, if applicable', max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.Network')),
            ],
            options={
                'ordering': ['-pub_date', 'title'],
            },
        ),
    ]
