# Generated by Django 3.0 on 2019-12-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='network',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nonprofit',
            options={},
        ),
        migrations.AlterField(
            model_name='network',
            name='pub_date',
            field=models.DateTimeField(default='timezone.now()', verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='nonprofit',
            name='title',
            field=models.CharField(help_text='Enter the network name', max_length=75),
        ),
    ]
