# Generated by Django 3.0 on 2019-12-10 01:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20191208_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonprofit',
            name='address',
        ),
        migrations.RemoveField(
            model_name='nonprofit',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='nonprofit',
            name='lon',
        ),
        migrations.AddField(
            model_name='nonprofit',
            name='_address',
            field=models.CharField(blank=True, help_text='Enter the nonprofit address, if applicable', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nonprofit',
            name='_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='nonprofit',
            name='_lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='network',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='network',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 10, 1, 57, 38, 469030, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='nonprofit',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='nonprofit',
            name='phone',
            field=models.CharField(blank=True, help_text='Enter a phone number in the format 111-111-1111', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='nonprofit',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 10, 1, 57, 38, 497817, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='nonprofit',
            name='src_file',
            field=models.ImageField(blank=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='nonprofit',
            name='src_link',
            field=models.URLField(blank=True, help_text='Enter a url for an image'),
        ),
        migrations.AlterField(
            model_name='nonprofit',
            name='website',
            field=models.URLField(blank=True, help_text='Enter the nonprofit website url, if applicable', null=True),
        ),
    ]
