# Generated by Django 3.0 on 2019-12-10 02:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20191209_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nonprofit',
            old_name='_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='nonprofit',
            old_name='_lat',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='nonprofit',
            old_name='_lon',
            new_name='lon',
        ),
        migrations.AlterField(
            model_name='network',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 10, 2, 13, 16, 134407, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='nonprofit',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 10, 2, 13, 16, 164568, tzinfo=utc), verbose_name='date published'),
        ),
    ]
