# Generated by Django 3.0 on 2019-12-10 02:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20191209_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 10, 2, 48, 16, 359426, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='nonprofit',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 10, 2, 48, 16, 388150, tzinfo=utc), verbose_name='date published'),
        ),
    ]
