# Generated by Django 3.0.8 on 2020-10-21 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('network', '0004_nonprofit_nonprofit_reps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='src_file',
            field=models.ImageField(blank=True, help_text='Submit a file for an image representing the network location', null=True, upload_to='network_images'),
        ),
        migrations.AlterField(
            model_name='network',
            name='src_link',
            field=models.URLField(blank=True, help_text='Enter a url for an image representing the network location', null=True),
        ),
        migrations.AlterField(
            model_name='nonprofit',
            name='description',
            field=models.CharField(blank=True, help_text='What kind of work will volunteers be doing here?', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='nonprofit',
            name='src_file',
            field=models.ImageField(blank=True, help_text='Upload an image representing the nonprofit location', null=True, upload_to='nonprofit_images'),
        ),
        migrations.AlterField(
            model_name='nonprofit',
            name='src_link',
            field=models.URLField(blank=True, help_text='Enter a url for an image representing the nonprofit location', null=True),
        ),
        migrations.CreateModel(
            name='RepApplicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, help_text="If you'd like to use a different email address for your application, please enter it here", max_length=254, null=True)),
                ('photo', models.ImageField(blank=True, help_text='Upload an image providing proof that you can represent this nonprofit (examples include a photo of you in uniform, a check/direct deposit, a log sheet of your hours, etc)', null=True, upload_to='applicant_images')),
                ('text', models.CharField(blank=True, help_text='Is there anything else that could show that you have a connection to this nonprofit?', max_length=1024, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved', models.BooleanField(default=False)),
                ('nonprofit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='network.Nonprofit')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
