# Generated by Django 3.0.8 on 2020-10-21 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20201021_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repapplicant',
            old_name='photo',
            new_name='src_file',
        ),
    ]
