# Generated by Django 3.0.8 on 2020-10-29 02:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('network', '0006_auto_20201021_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonprofit',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='network',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='network',
            name='src_file',
            field=models.ImageField(blank=True, help_text='Submit a file for an image representing the network location', null=True, upload_to='network_images/'),
        ),
        migrations.AlterField(
            model_name='nonprofit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nonprofit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nonprofit',
            name='phone',
            field=models.CharField(blank=True, help_text='Enter a phone number in the format 111-111-1111', max_length=12, null=True, validators=[django.core.validators.RegexValidator('\\d{3}-\\d{3}-\\d{4}')]),
        ),
        migrations.AlterField(
            model_name='nonprofit',
            name='src_file',
            field=models.ImageField(blank=True, help_text='Upload an image representing the nonprofit location', null=True, upload_to='nonprofit_images/'),
        ),
        migrations.AlterField(
            model_name='repapplicant',
            name='src_file',
            field=models.ImageField(blank=True, help_text='Upload an image providing proof that you can represent this nonprofit (examples include a photo of you in uniform, a check/direct deposit, a log sheet of your hours, etc)', null=True, upload_to='applicant_images/'),
        ),
    ]
