# Generated by Django 3.0 on 2019-12-10 02:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20191209_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 10, 2, 54, 16, 835778, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='nonprofit',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 10, 2, 54, 16, 865349, tzinfo=utc), verbose_name='date published'),
        ),
    ]
