# Generated by Django 3.0 on 2019-12-10 03:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20191209_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonprofit',
            name='refreshCoords',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='network',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='nonprofit',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 10, 3, 24, 6, 70905, tzinfo=utc), verbose_name='date published'),
        ),
    ]
