# Generated by Django 3.0 on 2019-12-30 22:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20191209_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonprofit',
            name='refreshCoords',
        ),
        migrations.AddField(
            model_name='nonprofit',
            name='flagged',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='nonprofit',
            name='email',
            field=models.EmailField(blank=True, help_text='Please enter a relevant email for volunteering, if applicable', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='nonprofit',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 30, 22, 10, 57, 331892, tzinfo=utc), verbose_name='date published'),
        ),
    ]
