# Generated by Django 3.0 on 2019-12-30 23:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_auto_20191230_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nonprofit',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 30, 23, 17, 13, 722218, tzinfo=utc), verbose_name='date published'),
        ),
    ]
