# Generated by Django 2.1.5 on 2020-01-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_auto_20200101_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-name']},
        ),
        migrations.AlterField(
            model_name='network',
            name='src_file',
            field=models.ImageField(blank=True, help_text='Submit a file for an image representing the network location', upload_to=None),
        ),
        migrations.AlterField(
            model_name='network',
            name='src_link',
            field=models.URLField(blank=True, help_text='Enter a url for an image representing the network location'),
        ),
        migrations.AlterField(
            model_name='network',
            name='title',
            field=models.CharField(default='', help_text='What town/city/location will this network be representing?', max_length=75, unique='True'),
        ),
    ]
