# Generated by Django 2.1.5 on 2020-01-08 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_auto_20200107_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
    ]
