# Generated by Django 2.1.5 on 2020-01-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_auto_20200107_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonprofit',
            name='nonslug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='nonprofit',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nonprofit',
            name='src_file',
            field=models.ImageField(blank=True, help_text='Submit a file for an image representing the network location', upload_to=None),
        ),
        migrations.AlterField(
            model_name='nonprofit',
            name='src_link',
            field=models.URLField(blank=True, help_text='Enter a url for an image representing the network location'),
        ),
    ]
