# Generated by Django 2.1.5 on 2020-01-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_auto_20200112_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonprofit',
            name='nonslug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
