# Generated by Django 2.1.5 on 2020-01-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_auto_20200112_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='title',
            field=models.CharField(default='', help_text='What town/city/location will this network be representing?', max_length=75, unique=True),
        ),
    ]
