# Generated by Django 3.0.2 on 2020-01-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_auto_20200112_1646'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='nonprofit',
            constraint=models.UniqueConstraint(fields=('network', 'title'), name='unique_np_naming'),
        ),
    ]
