# Generated by Django 3.0.2 on 2020-01-13 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0021_auto_20200112_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='slug',
            new_name='netslug',
        ),
    ]
