# Generated by Django 3.0.2 on 2020-01-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0023_auto_20200112_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='src_file',
            field=models.ImageField(blank=True, help_text='Submit a file for an image representing the network location', upload_to='images/network_images'),
        ),
        migrations.AlterField(
            model_name='nonprofit',
            name='src_file',
            field=models.ImageField(blank=True, help_text='Submit a file for an image representing the network location', upload_to='images/nonprofit_images'),
        ),
    ]
