# Generated by Django 3.0.2 on 2020-01-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0025_auto_20200119_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonprofit',
            name='description',
            field=models.CharField(blank=True, help_text='What kind of work will volunteers be doing here?', max_length=1024, null=True),
        ),
    ]
