# Generated by Django 3.0.3 on 2020-03-28 18:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='What is the name of this organization?', max_length=75, unique=True)),
                ('description', models.CharField(blank=True, help_text='A short description', max_length=500, null=True)),
                ('src_link', models.URLField(blank=True, help_text='Enter a url for an image representing the organization')),
                ('src_file', models.ImageField(blank=True, help_text='Submit a file for an image representing the organization', upload_to='network_images')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('public', models.BooleanField(default=True)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mod', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='Does this goal have a specific name?', max_length=75)),
                ('description', models.CharField(blank=True, help_text='A short description of the goal', max_length=500, null=True)),
                ('hours', models.IntegerField(blank=True, help_text='How many hours are wanted?', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='only hours after this time will count to this goal')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='only hours before this time will count to this goal')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.Organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
