# Generated by Django 3.0.3 on 2020-04-10 02:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_auto_20200409_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='user',
        ),
        migrations.AddField(
            model_name='invitation',
            name='max_uses',
            field=models.IntegerField(blank=True, help_text='What is the maximum number of times this invitation can be used? Leave blank for unlimited', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Maximum Uses'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='uses',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
