# Generated by Django 3.0.3 on 2020-04-10 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0005_auto_20200409_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='uses',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
