# Generated by Django 3.0.5 on 2020-04-18 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20200128_2104'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0008_auto_20200415_0249'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=75, null=True)),
                ('message', models.CharField(default='', max_length=1000)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('allows_children', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('nonprofit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network.Nonprofit')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.CharField(blank=True, help_text='If this organization has a physical address, enter if applicable', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, help_text='Enter a relevant email to contact this organization, if applicable', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, help_text='Enter a phone number in the format 111-111-1111, if applicable', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, help_text='If this organization has a website different from here, enter if applicable', null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.CharField(blank=True, help_text='A short description. This could be a mission statement, or something else.', max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='Textp',
        ),
        migrations.AddField(
            model_name='textpost',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.Organization'),
        ),
        migrations.AddField(
            model_name='textpost',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='orgs.TextPost'),
        ),
    ]
