# Generated by Django 3.0.8 on 2020-11-01 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgs', '0009_auto_20200418_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textpost',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='textpost',
            name='message',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='textpost',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='textpost',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
