# Generated by Django 3.0.8 on 2020-11-12 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20201029_0200'),
        ('orgs', '0010_auto_20201101_2253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textpost',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterField(
            model_name='invitation',
            name='expiration',
            field=models.DurationField(blank=True, help_text='after this time, this link will no longer be valid', null=True),
        ),
        migrations.AlterField(
            model_name='textpost',
            name='allows_children',
            field=models.BooleanField(default=True, help_text='Allow replies to this announcement'),
        ),
        migrations.AlterField(
            model_name='textpost',
            name='nonprofit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcement', to='network.Nonprofit'),
        ),
        migrations.AlterField(
            model_name='textpost',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcement', to='orgs.Organization'),
        ),
    ]
