# Generated by Django 3.0.8 on 2020-11-12 17:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0011_auto_20201112_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
