# Generated by Django 3.1.4 on 2020-12-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0015_invitation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.CharField(blank=True, help_text='A short description. This could be a mission statement, or something else.', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, help_text='Enter a relevant email to contact this organization, if applicable', max_length=255, null=True),
        ),
    ]
