# Generated by Django 3.1.4 on 2020-12-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0016_auto_20201208_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='request',
            name='token',
            field=models.CharField(max_length=8),
        ),
    ]
