# Generated by Django 3.1.4 on 2020-12-26 19:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0017_auto_20201222_0437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='goal',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='goal',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name='only hours before or on this date will count to this goal'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='start',
            field=models.DateField(blank=True, null=True, verbose_name='only hours after to or on this date will count to this goal'),
        ),
    ]
