# Generated by Django 3.0.3 on 2020-03-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, help_text='This is the name that others will see you as (if specified)', max_length=50, null=True),
        ),
    ]
