# Generated by Django 3.0.3 on 2020-02-05 01:39

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc
import recurrence.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cal', '0002_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='starting time')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ending time')),
                ('all_day', models.BooleanField(default=False, verbose_name='will this event last the entire day')),
                ('repeat', recurrence.fields.RecurrenceField()),
                ('end_repeat', models.DateTimeField(default=datetime.datetime(2021, 2, 4, 1, 39, 32, 622769, tzinfo=utc), verbose_name='end repeat date')),
            ],
        ),
    ]
