# Generated by Django 3.0.3 on 2020-02-05 02:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_repeat',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 4, 2, 1, 59, 900739, tzinfo=utc), verbose_name='end repeat date'),
        ),
    ]
