# Generated by Django 3.0.3 on 2020-02-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_auto_20200229_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='repeat',
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence',
            field=models.CharField(blank=True, help_text='Will this event ever repeat?', max_length=200, null=True),
        ),
    ]
