# Generated by Django 3.0.3 on 2020-03-28 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
        ('cal', '0005_auto_20200229_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orgs.Organization'),
        ),
        migrations.AddField(
            model_name='event',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='cal.Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, help_text='Describe the event briefly. What type of work will be done?', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('VO', 'Volunteering Opportunity'), ('AA', 'Account Anniversary'), ('CE', 'Community Event'), ('NV', 'Non-Volunteering Event')], help_text='What type of event will this be?', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='recurrence',
            field=models.CharField(blank=True, help_text='Will this event ever repeat?', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, help_text='What is the name of the event?', max_length=75, null=True),
        ),
    ]
