# Generated by Django 3.0.3 on 2020-02-05 02:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20200128_2104'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0005_auto_20200204_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.Network'),
        ),
        migrations.AddField(
            model_name='event',
            name='nonprofit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.Nonprofit'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_repeat',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 4, 2, 13, 0, 952792, tzinfo=utc), verbose_name='end repeat date'),
        ),
    ]
