# Generated by Django 3.0.3 on 2020-03-28 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0006_auto_20200328_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='user_calendar',
            new_name='custom_calendar',
        ),
    ]
