# Generated by Django 3.0.3 on 2020-02-05 02:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20200128_2104'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0006_auto_20200204_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='network',
        ),
        migrations.RemoveField(
            model_name='event',
            name='nonprofit',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.AlterField(
            model_name='event',
            name='end_repeat',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 4, 2, 25, 33, 807938, tzinfo=utc), verbose_name='end repeat date'),
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network.Network')),
                ('nonprofit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network.Nonprofit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
