# Generated by Django 3.0.3 on 2020-02-05 02:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0007_auto_20200204_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='calendar',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cal.Calendar'),
        ),
        migrations.AlterField(
            model_name='event',
            name='all_day',
            field=models.BooleanField(default=False, help_text='will this event last the entire day', verbose_name='all day?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(default='', help_text='Describe the event briefly. What type of work will be done?', max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_repeat',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 4, 2, 28, 43, 544675, tzinfo=utc), verbose_name='end repeat date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='', help_text='What is the name of the event?', max_length=75),
        ),
    ]
