# Generated by Django 3.0.3 on 2020-02-05 02:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0008_auto_20200204_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='title',
            field=models.CharField(default='', help_text='What is the name of this calendar?', max_length=75),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_repeat',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 4, 2, 29, 49, 81073, tzinfo=utc), verbose_name='end repeat date'),
        ),
    ]
