# Generated by Django 3.0.3 on 2020-02-05 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0009_auto_20200204_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_repeat',
        ),
    ]
