# Generated by Django 3.0.5 on 2020-04-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0009_event_excluded_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='token',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
