# Generated by Django 3.0.5 on 2020-04-19 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0010_event_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='custom_calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendars', to='cal.Calendar'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='calendar',
        ),
        migrations.AddField(
            model_name='event',
            name='calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='cal.Calendar'),
        ),
        migrations.AlterField(
            model_name='event',
            name='token',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
