# Generated by Django 3.0.3 on 2020-02-05 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0010_remove_event_end_repeat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['title']},
        ),
    ]
