# Generated by Django 3.0.3 on 2020-02-06 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0011_auto_20200204_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='verified',
            field=models.ForeignKey(blank=True, help_text='has a nonprofit representative verified this network?', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
