# Generated by Django 3.0.3 on 2020-02-06 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0012_event_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={},
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='title',
        ),
    ]
