# Generated by Django 3.0.5 on 2020-04-19 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0012_auto_20200419_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='nonprofit_reps',
        ),
    ]
