# Generated by Django 3.0.5 on 2020-04-19 02:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0013_remove_event_nonprofit_reps'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='total_attending',
            field=models.IntegerField(default='0', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='sign_up_slots',
            field=models.IntegerField(blank=True, help_text='How many sign up slots are being offered?', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
