# Generated by Django 3.0.3 on 2020-02-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0013_auto_20200205_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='title',
            field=models.CharField(default='Global', help_text='What is the name of this calendar?', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
