# Generated by Django 3.0.5 on 2020-04-19 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0014_auto_20200419_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='token',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
