# Generated by Django 3.0.3 on 2020-02-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0014_calendar_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='title',
        ),
        migrations.AddField(
            model_name='calendar',
            name='isGlobal',
            field=models.BooleanField(default=False),
        ),
    ]
