# Generated by Django 3.0.5 on 2020-04-19 06:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0015_calendar_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='recurrence',
        ),
        migrations.AddField(
            model_name='event',
            name='rrule',
            field=models.CharField(blank=True, help_text='Will this event ever repeat?', max_length=700, null=True, validators=[django.core.validators.RegexValidator('[^><\\"\\\'&a-mo-z!@#$%^&*()+_]+', 'This string must be in the rrule format.')]),
        ),
    ]
