# Generated by Django 3.0.3 on 2020-02-06 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20200128_2104'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0015_auto_20200205_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='network',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network.Network'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='nonprofit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='network.Nonprofit'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
