# Generated by Django 3.0.5 on 2020-07-12 22:13

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0016_auto_20200419_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance', to='cal.Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='rrule',
            field=models.CharField(blank=True, help_text='Will this event ever repeat?', max_length=700, null=True, validators=[django.core.validators.RegexValidator('[^><.\\"\\\'&a-mo-z!@#$%^&*()+_\\s]+', 'This string must be in the rrule format.')]),
        ),
        migrations.AlterField(
            model_name='excludeddates',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='excluded date'),
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='attendees', to='cal.Attendee'),
        ),
    ]
