# Generated by Django 3.0.3 on 2020-02-07 02:04

from django.db import migrations
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0017_calendar_network_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='repeat',
            field=recurrence.fields.RecurrenceField(blank=True, null=True),
        ),
    ]
