# Generated by Django 3.0.5 on 2020-07-12 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0017_auto_20200712_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='total_attending',
        ),
    ]
