# Generated by Django 3.0.3 on 2020-02-08 18:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cal', '0018_auto_20200206_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='excluded_calendars',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excludedcal', to='cal.Calendar'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='user_calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercal', to='cal.Calendar'),
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='attendees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('VO', 'Volunteering Opportunity'), ('AA', 'Account Anniversary'), ('CE', 'Community Event'), ('NV', 'Non-Volunteering Event')], default='NV', help_text='What type of event will this be?', max_length=2),
        ),
        migrations.AddField(
            model_name='event',
            name='nonprofit_reps',
            field=models.ManyToManyField(blank=True, related_name='nonreps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='sign_up_slots',
            field=models.IntegerField(blank=True, help_text='What is the maximum number of people that will be at this event?', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='network_calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='networkcal', to='cal.Calendar'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='calendar',
        ),
        migrations.AddField(
            model_name='event',
            name='calendar',
            field=models.ManyToManyField(default='', to='cal.Calendar'),
        ),
    ]
