# Generated by Django 3.0.8 on 2020-08-11 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0020_auto_20200712_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
