# Generated by Django 3.0.8 on 2020-10-15 00:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0024_auto_20200812_0300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['parent__id', '-start_date']},
        ),
        migrations.AddField(
            model_name='attendee',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendee',
            name='uuid',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='ending time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='rrule',
            field=models.CharField(blank=True, help_text='Will this event ever repeat?', max_length=700, null=True, validators=[django.core.validators.RegexValidator('(?P<DTSTART>DTSTART:\\d{8}T\\d{6}Z?\\\\n)?RRULE:((?P<FREQ>FREQ=(MONTHLY|YEARLY|WEEKLY|DAILY))?(?P<UNTIL>UNTIL=\\d{8}T\\d{6}Z?)?(?P<COUNT>COUNT=\\d+)?(?P<INTERVAL>INTERVAL=\\d+)?(?P<WKST>WKST=(MO|TU|WE|TH|FR|SA|SU))?(?P<BYDAY>BYDAY=(((MO)?(TU)?(WE)?(TH)?(FR)?(SA)?(SU)?),?)+)?(?P<BYMONTH>BYMONTH=(\\d{1,2},?)+)?(?P<BYMONTHDAY>BYMONTHDAY=(\\d{1,2},?)+)?(?P<BYYEARDAY>BYYEARDAY=(\\d{1,3},?)+)?(?P<BYWEEKNO>BYWEEKNO=(\\d{1,2},?)+)?(?P<BYSETPOS>BYSETPOS=(-?\\d{1,2},?)+)?;?)+(?P<EXDATE>\\\\nEXDATE:((\\d{8}(T\\d{6}Z?)?),?)+)?', 'This string must be in the rrule format.')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='starting time'),
        ),
    ]
