# Generated by Django 3.0.8 on 2020-10-21 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0025_auto_20201015_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='all_day',
            field=models.BooleanField(help_text='will this event last the entire day', null=True, verbose_name='all day?'),
        ),
    ]
