# Generated by Django 3.1.4 on 2020-12-08 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0026_auto_20201021_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='network_calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nonprofitcal', to='cal.calendar'),
        ),
    ]
