# Generated by Django 3.1.4 on 2020-12-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0027_auto_20201208_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='token',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='token',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
