# Generated by Django 3.1.4 on 2020-12-08 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import logs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cal', '0027_auto_20201208_1934'),
        ('network', '0007_auto_20201029_0200'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('created_on', models.DateField(default=django.utils.timezone.now)),
                ('duration', models.DurationField(default=0, validators=[logs.models.duration_validator])),
                ('description', models.CharField(blank=True, help_text='A short description of the work that you completed. Can include who supervised you.', max_length=512, null=True)),
                ('attendee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cal.attendee')),
                ('nonprofit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network.nonprofit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nonprofitrep', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
