# Generated by Django 3.1.4 on 2020-12-22 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import logs.models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20201029_0200'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='log',
            name='duration',
            field=models.DurationField(default=0, help_text='How long you volunteered for (in the form HH:MM)', validators=[logs.models.duration_validator]),
        ),
        migrations.AlterField(
            model_name='log',
            name='nonprofit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log', to='network.nonprofit'),
        ),
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='log',
            name='verified',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_log', to=settings.AUTH_USER_MODEL),
        ),
    ]
