# Generated by Django 3.1.4 on 2020-12-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20201222_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
