# Generated by Django 3.1.4 on 2020-12-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_log_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='token',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
